apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: issuer-bot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: issuer-bot
    spec:
      containers:
      - name: issuer-bot-api
        imagePullPolicy: Always
        image: pyama/issuer-bot:latest
        tty: true
        ports:
        - containerPort: 3000
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3000
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3000
        env:
          - name: REDIS_URL
            value: "redis://redis-service:6379"
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: issuer-bot
                key: slack-signing-token
          - name: SLACK_WORKSPACE_URL
            value: "https://your.slack.com"
          - name: TZ
            value: Asia/Tokyo
          - name: RAILS_ENV
            value: "production"
          - name: SLACK_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: issuer-bot
                key: slack-api-token
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: issuer-bot
                key: github-token
          - name: MYSQL_HOST
            value: "your db"
          - name: MYSQL_USER
            value: "issuer-bot"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: issuer-bot
                key: mysql-password
