apiVersion: v1
kind: Service
metadata:
  name: issuer-bot
spec:
  type: LoadBalancer
  selector:
    name: issuer-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: issuer-bot
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
